### ISSUE TITLE
Possibility to add a Message Inspector

### ISSUE THREAD

**Issue by alexandrudanpop** [autofac/Autofac.Wcf#12]
Please add a possibility to inject an  IDispatchMessageInspector for a certain WCF service implementation.

If I use default WCF way of doing it (https://msdn.microsoft.com/en-us/library/system.servicemodel.dispatcher.idispatchmessageinspector.aspx?f=255&MSPPError=-2147217396) I get Singleton instance of an IDispatchMessageInspector and can not use constructor injection for it.

**Comment by tillig** [comment]
There's an article [here](https://msdn.microsoft.com/en-us/library/ff183867.aspx) that shows how an `IInstanceProvider` can be enhanced to apply behaviors. I'm unclear on how this interacts with (or ignores?) behaviors applied through attributes or XML configuration.

It sounds like something interesting, but with the momentum behind some of the other integrations this will likely be a lower priority thing, especially since it'll require a lot of deep diving into the WCF runtime to ensure all the different combinations of configuration will all still work together.

**Totally open to a PR for this.**

**Comment by alexandrudanpop** [comment]
Investigated this further. This functionality is already present in Ninject. Would be really nice to have it also in Autofac.Wcf
https://stackoverflow.com/questions/20687932/wcf-ninject-getting-ninject-kernel-into-an-idispatchmessageinspector-instanc

**Comment by johneking** [comment]
I've had a look at this and a comprehensive solution might be tricky for a few reasons. Primarily, the instantiation of messageinspectors isn't extensible in WCF in the same way as the service instances themselves are. These and other types of extension objects are added to service endpoints or the service host effectively as singletons on app-startup, and generally Behaviours just act as factories for doing so (this appears to also be true for the Ninject implementation).

I think the original request actually breaks down into a few different requirements:

**1. General DI**
An easy + safe way to inject inspectors as singletons is just to create a custom behaviour which acts as a factory for the real behaviour we want to inject dependencies to. e.g.
given:
    
```
public class Inspector : IDispatchMessageInspector, IParameterInspector { [message inspector logic] }
// general behaviour to apply an injected IDispatchMessageInspector
public class EndpointInspectorInserter : IEndpointBehavior
{
    private readonly IDispatchMessageInspector _inspector;
    public EndpointInspectorInserter(IDispatchMessageInspector inspector){_inspector = inspector;}    
    public void ApplyDispatchBehavior(ServiceEndpoint endpoint, EndpointDispatcher endpointDispatcher)
    {
        endpointDispatcher.DispatchRuntime.MessageInspectors.Add(_inspector);
    }    
    [ ... ]
}
```
    
we could add:
    
```
public class AutofacEndpointBehavior<T> : IEndpointBehavior where T : class, IEndpointBehavior
{
    private readonly ILifetimeScope _scope;
    private T _innerBehaviorInstance;
    private T InnerBehaviour => _innerBehaviorInstance ?? (_innerBehaviorInstance = ResolveNewBehaviour());

    private T ResolveNewBehaviour()
    {
        return _scope.Resolve<T>();
    }
    public AutofacEndpointBehavior(ILifetimeScope scope)
    {
        _scope = scope;
    }
    public void ApplyDispatchBehavior(ServiceEndpoint endpoint, EndpointDispatcher endpointDispatcher)
    {
        InnerBehaviour.ApplyDispatchBehavior(endpoint, endpointDispatcher);
    }
    [ ... ]
}
```
    
The same approach applies for contract and service behaviours. That's potentially slightly useful on its own but would still need to be applied programatically by default. It works fairly generically though and automatically applies to anything behaviours can do. Example usage:

```
ServiceHost host = new ServiceHost(typeof(TestService));
host.AddDependencyInjectionBehavior<ITestService>(container);
host.Description.Endpoints.First().EndpointBehaviors.Add(new AutofacEndpointBehavior<EndpointInspectorInserter>(container));
```
    
**2. Instances per dependency / per request**

As above, the objects we're trying to instantiate are treated as singletons by the service itself. We could circumvent this with proxy classes for each type of extension we want to modify (MessageInspectors, ErrorHandlers etc.) which manage scopes internally, but this requires the code to get pretty specific and potentially a bit messy. It doesn't look super-easy to access the per-operation context uniformly either, so we might be limited to creating a scope for every operation the MessageInspector executes, assuming it doesn't have a big performance impact. e.g.
    
```
public class AutofacMessageInspectorProxy<T> : IDispatchMessageInspector where T : IDispatchMessageInspector
{
    private readonly ILifetimeScope _rootScope;
    private readonly string _registrationKey;

    public AutofacMessageInspectorProxy(ILifetimeScope scope, string registrationKey = null)
    {
        _rootScope = scope;
        _registrationKey = registrationKey;
    }
    private Owned<T> GetInspector()
    {
        return _rootScope.ResolveKeyed<Owned<T>>(_registrationKey);
    }
    public object AfterReceiveRequest(ref Message request, IClientChannel channel, InstanceContext instanceContext)
    {
        using (var inspector = GetInspector())
        {
            return inspector.Value.AfterReceiveRequest(ref request, channel, instanceContext);
        }
    }
    public void BeforeSendReply(ref Message reply, object correlationState)
    {
        using (var inspector = GetInspector())
        {
            inspector.Value.BeforeSendReply(ref reply, correlationState);
        }
    }
}
```
**3. Service + endpoint DI from config file settings**
Issue 1: requires a new reference to System.Configuration in order to derive from BehaviorExtensionElement
Issue 2: would require a static LifetimeScope, similar to ServiceHosts initialised from config, and potentially pointed to the same global container, e.g.
    
```
public class AutofacEndpointBehaviorExtensionElement<T> : BehaviorExtensionElement where T : class, IEndpointBehavior
{
    private ILifetimeScope _scope;
    protected override object CreateBehavior()
    {
        // this needs to be set at start-up, the same as for ServiceHosts
        _scope = AutofacHostFactory.Container.BeginLifetimeScope();
        return new AutofacEndpointBehavior<T>(_scope, Key);
    }
    public override Type BehaviorType => typeof(T);
    [ConfigurationProperty("key", DefaultValue = null, IsRequired = false)]
    public string Key
    {
        get { return (string)this["key"]; }
        set { this["key"] = value; }
    }
}
```
    
**4. Ability to match MessageInspector registrations to specific endpoints**

We could introduce a parameter into the custom behaviours (as above) which links to a keyed registration without too much trouble. That would allow it to be set per endpoint, e.g. from config it might look like:
    
```
<extensions>
    <behaviorExtensions>
        <add name="autofacInspector" type="[namespace].InspectorBehaviourElement, [assembly]" />
    </behaviorExtensions>
</extensions>

<endpointBehaviors>
    <behavior name="inspectorInjectionBehaviour">
      <autofacInspector key="abc" />
    </behavior>
</endpointBehaviors>

<endpoint address="" binding="netNamedPipeBinding" contract="[namespace].ITestService" behaviorConfiguration="inspectorInjectionBehaviour" />

```

What's the view on the value of each of these?

My gut feel is that the per-dependency proxy classes are a bit messy and would require bloating out the code quite a bit to cover all the different types of proxies (assuming that a full solution would require it), so it might not be worth going down that route unless there's a real need for it.

Adding in the config extensions just for basic DI gives a bit of value - without it, if users need to add behaviours to endpoints programmatically then the new code itself doesn't do much in advance of just resolving an inspector up-front, which could easily be done manually (example below). But that's a trade-off with the addition of the dependency on System.Configuration. 

Given that it's possible to achieve the most basic required functionality without anything new (but a bit of extra fiddling in the application code), does anyone have a view on whether a basic implementation of DI along with config extensions would be worth adding or not?

```
// example of manually injecting a MessageInspector and adding it to an endpoint programmatically using the current Autofac.Wcf version

var builder = new ContainerBuilder();
builder.RegisterType<TestService>()
    .As<ITestService>();
builder.RegisterType<Inspector>()
    .Keyed<IDispatchMessageInspector>("inspector1");  // demonstrating how inspectors could be linked to endpoints
var container = builder.Build();

using (var inspectorScope = container.BeginLifetimeScope())
{
    ServiceHost host = new ServiceHost(typeof(TestService));
    host.AddDependencyInjectionBehavior<ITestService>(container);

    var inspector = inspectorScope.ResolveKeyed<IDispatchMessageInspector>("inspector1");
    host.Description.Endpoints.First(e=>e.Name == "Endpoint1")
        .EndpointBehaviors.Add(new EndpointInspectorInserterBehaviour(inspector));

    host.Open();
    Console.ReadLine();
    host.Close();
}
```

**Comment by tillig** [comment]
It sounds like there are a lot of moving pieces that need to come together to support something like this:

- The service host - in our case, we use `AutofacServiceHostFactory` or `AutofacWebServiceHostFactory`, which wire up the instance provider.
- The behavior - that which attaches the message inspector to the appropriate endpoints.
- The inspector - that which needs things injected into it.
- Configuration - support via XML and programmatic.

We do have that `AddDependencyInjectionBehavior` extension for the standard service host, but IIRC that came after we figured out how to get things working through our custom service host factory.

There's also an interesting challenge where behaviors/inspectors are generally singletons but services can be per-call or singleton. I imagine for per-call services ("per request") folks are going to want per-call inspectors, which won't really be possible.

**Given there's not a lot of investment in general in WCF on the Microsoft side, I'd probably pass on adding support here. It's going to be a lot of effort and won't help a proportional number of folks.**

Instead, we should probably keep an eye on things like [CoreWCF](https://github.com/CoreWCF/CoreWCF) where the service-side of WCF is getting ported to .NET Core. I assume DI will be far more available there and we'll have more opportunity to make things better.

What do you think?

**Comment by johneking** [comment]
Yep, I agree, the current WCF internals aren't designed to enable what we'd ideally do so it probably doesn't make sense to support this functionality for the time being - happy to revisit when a newer service-side framework is production-ready. In the short term, additional XML config features would be convenient for some scenarios but there are functional workarounds for those as things stand anyway.

**Comment by tillig** [comment]
Okay, then let's close this as won't fix.
